apiVersion: v1
kind: Service
metadata:
  name: capitalise
  namespace: munge
  labels:
    app: capitalise
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: capitalise
  type: ClusterIP
