apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: single-pod
  labels:
    app: single-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: single-pod
  template:
    metadata:
      labels:
        app: single-pod
    spec:
      containers:
        - name: frontend
          image: tophatsteve/frontend:latest
          env:
          - name: PORT
            value: "80"
          - name: REVERSE_SERVICE_HOST
            value: "localhost"
          - name: REVERSE_SERVICE_PORT
            value: "8080"
          - name: CAPITALISE_SERVICE_HOST
            value: "localhost"
          - name: CAPITALISE_SERVICE_PORT
            value: "8081"                                    
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "10Mi"
              cpu: "100m"          
        - name: reverse
          image: tophatsteve/reverse:latest
          env:
          - name: PORT
            value: "8080"                                  
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: "10Mi"
              cpu: "100m"   
        - name: capitalise
          image: tophatsteve/capitalise:latest
          env:
          - name: PORT
            value: "8081"                                 
          ports:
          - containerPort: 8081
          resources:
            limits:
              memory: "10Mi"
              cpu: "100m"   
         
