apiVersion: v1
kind: Service
metadata:
  name: reverse
  namespace: munge
  labels:
    app: reverse
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: reverse
  type: ClusterIP
